language: python
sudo: required
python:
- '3.6'
install:
- pip install -r requirements.txt -r requirements-dev.txt
- sudo apt-get update -qq
- sudo apt-get install -y openvpn
env:
- CFG_PATH=config/georef.example.cfg
script:
- make test_mock
- make code_style
deploy:
  - provider: script
    skip_cleanup: true
    script: 'bash deploy/travis.sh production'
    on:
      tags: true
      branch: master
      repo: datosgobar/georef-ar-api
  - provider: script
    skip_cleanup: true
    script: 'bash deploy/travis.sh staging'
    on:
      branch: master
      repo: datosgobar/georef-ar-api
  - provider: script
    skip_cleanup: true
    script: 'bash deploy/travis.sh development'
    on:
      branch: development
      repo: datosgobar/georef-ar-api
before_deploy:
- openssl aes-256-cbc -K $encrypted_4c0bf4b7e010_key -iv $encrypted_4c0bf4b7e010_iv
  -in deploy/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- openssl aes-256-cbc -K $encrypted_5f43eadfe7ce_key -iv $encrypted_5f43eadfe7ce_iv
  -in deploy/travis_georef.ovpn.enc -out travis_georef.ovpn -d
- sudo openvpn --config travis_georef.ovpn --daemon --verb 0 --writepid openvpn.pid
- sleep 10
- sudo ip link set tun0 mtu 1200
after_deploy:
- sudo kill -SIGTERM $(cat openvpn.pid)
