site_name: API del Servicio de Normalización de Datos Geográficos de Argentina
site_url: http://apis.datos.gob.ar/georef/
site_description: Documentación de la API del Servicio de Normalización de Datos Geográficos de la República Argentina
site_author: Datos Argentina

repo_url: https://github.com/datosgobar/georef-ar-api
edit_uri: ""

nav:
  - Inicio: index.md
  - Usuarios:
    - Ejemplos de uso: quick-start.md
    - Consultas por lotes: bulk.md
    - Operaciones con geometrías: geom-operations.md
    - Usar en planillas de cálculo: spreadsheet-integration.md
    - Usar en Python: python-usage.md
    - Autenticarse con JWT: jwt-token.md
    - Referencia API: https://datosgobar.github.io/georef-ar-api/open-api
    - Condiciones de uso: terms.md
  - Aplicaciones: applications.md
  - Desarrolladores:
    - Ambiente de desarrollo y deploy: georef-api-development.md
    - Proceso de ETL y Datos: georef-api-data.md
    - Historial de versiones: history.md
    - Instalación de Python 3.6: python3.6.md

docs_dir: docs/src
site_dir: docs/site

google_analytics: ['UA-91435482-1', "https://datosgobar.github.io/georef-ar-api/"]

theme:
  name: datosgobar_docs
  highlightjs: true
  hljs_languages:
      - yaml
      - django
      - python

extra_css:
  - css/extra.css

plugins:
  - search:
      lang: es

markdown_extensions:
  - toc:
      permalink: True
  - attr_list
  - fenced_code
  - sane_lists
  - admonition
